### ISSUE TITLE
Remove provider from hcl

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gcp-atlantis#13]
The provider should only be in the root module, not in the consumable module.

By removing it, you may also be able to remove the project_id input.

https://github.com/bschaatsbergen/terraform-gcp-atlantis/blob/474dbae438ca7005f03a1de3b47f962c694e8cb1/main.tf#L1-L3

**Comment by bschaatsbergen** [comment]
Thanks for raising this issue @nitrocode, I'll get on it.
