### ISSUE TITLE
Expose entire container input and/or container image 

### ISSUE THREAD

**Issue by nitrocode** [bschaatsbergen/terraform-gcp-atlantis#16]
Its limiting to only support a conditional for the container image

It would be good to expose the entire container input or at least the full container image.

For example, what if i wanted to use a custom image or a custom tag?

https://github.com/bschaatsbergen/terraform-gcp-atlantis/blob/474dbae438ca7005f03a1de3b47f962c694e8cb1/atlantis.tf#L9

You may want to expose more inputs to the upstream module as well

You can also avoid having to put in additional logic for the dev tag https://github.com/bschaatsbergen/terraform-gcp-atlantis/issues/3.

**Comment by bschaatsbergen** [comment]
For the initial release of the module we can start with exposing the full container image, I agree that's a good point.
